name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  id-token: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
      GITHUB_TOKEN: ${{ secrets.SKM_GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          cache: true
#      - uses: docker/setup-buildx-action@v2
#      - name: setup-snapcraft
#        run: |
#          sudo apt-get update
#          sudo apt-get -yq --no-install-suggests --no-install-recommends install snapcraft
#      - name: dockerhub-login
#        if: startsWith(github.ref, 'refs/tags/v')
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#      - name: ghcr-login
#        if: startsWith(github.ref, 'refs/tags/v')
#        uses: docker/login-action@v2
#        with:
#          registry: ghcr.io
#          username: ${{ github.repository_owner }}
#          password: ${{ secrets.SKM_GITHUB_TOKEN }}
#      - name: snapcraft-login
#        if: startsWith(github.ref, 'refs/tags/v')
#        run: snapcraft login --with <(echo "${{ secrets.SNAPCRAFT_LOGIN }}")
      #      it's commented due to the bug in betteralig -apply. ref: https://github.com/dkorunic/betteralign/issues/4
      #      - name: sort-structs # sorting structs is a best-practice to improve memory usage and performance by reducing the padding between fields
      #        run: go run github.com/dkorunic/betteralign/cmd/betteralign@latest -apply ./...
      - name: mod-download
        run: |
          make vendor
      - uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --skip-validate
        env:
          GITHUB_TOKEN: ${{ secrets.SKM_GITHUB_TOKEN }}
          FURY_TOKEN: ${{ secrets.FURY_TOKEN }}
      - uses: actions/upload-artifact@v3
        with:
          name: release-artifacts
          path: |
            . 
            !./dist